 ; 从STRIN+1单元起有一个字符串，串长在STRIN单元中。另在NUMB单元中有一数N.
 ;要求在字符串第N个字符后插入一个字符‘？’。若N大于串长则不插入。

DATA SEGMENT
strin db 26,'ABCDEFGHIJKLMNOPQRSTUVWXYZ',' ',13,10,'$'
numb db  5
DATA ENDS
CODE SEGMENT
  ASSUME  CS:CODE,DS:DATA ,ES:DATA
START:
MOV AX,DATA
MOV DS,AX
MOV ES,AX
MOV DX,OFFSET STRIN+1
MOV AH,9
INT 21H
MOV CX,0
MOV CL,NUMB
MOV BX,0
MOV BL,STRIN
CMP CL, BL
JA  EXIT
LEA DI,STRIN[BX+1]
LEA SI,STRIN[BX]
SUB BX,CX
MOV CX,BX
STD
REP MOVSB
MOV BL,NUMB
MOV BH,0
MOV STRIN[BX+1],'?'
EXIT:
MOV DX,OFFSET STRIN+1
MOV AH,9
INT 21H
MOV AH,4CH
INT 21H
CODE  ENDS
  END START